// Data Leakage Prevention Rules (ModSecurity CRS 930)
export const DATA_LEAKAGE_RULES = [
  {
    id: 'data-sql-error',
    name: 'Data Leakage - SQL Error Messages',
    pattern: /(sql.*error|mysql.*error|ora-\d{5}|postgres.*error|sqlite.*error|sqlstate|syntax error|unexpected.*token|column.*not found)/i,
    field: 'response',
    severity: 'high',
    score: 80,
    category: 'data-leakage',
    description: 'SQL error message exposure',
    recommendation: 'Use generic error messages, log details server-side'
  },
  {
    id: 'data-stack-trace',
    name: 'Data Leakage - Stack Trace Exposure',
    pattern: /(stack trace|at\s+\w+\.\w+\s*\(|java\.lang\.|thrown.*exception|traceback|line \d+|file ".*\.py")/i,
    field: 'response',
    severity: 'high',
    score: 82,
    category: 'data-leakage',
    description: 'Stack trace or debug information exposed',
    recommendation: 'Disable debug mode in production'
  },
  {
    id: 'data-version-disclosure',
    name: 'Data Leakage - Version/Banner Disclosure',
    pattern: /(apache\/[\d.]+|nginx\/[\d.]+|microsoft-iis\/[\d.]+|php\/[\d.]+|python\/[\d.]+|ruby\/[\d.]+|tomcat\/[\d.]+|server:\s*[a-zA-Z]+\/[\d.]+)/i,
    field: 'headers',
    severity: 'medium',
    score: 65,
    category: 'data-leakage',
    description: 'Server version information in response headers',
    recommendation: 'Remove or mask server version headers'
  },
  {
    id: 'data-path-disclosure',
    name: 'Data Leakage - File Path Disclosure',
    pattern: /(\/home\/\w+|\/usr\/local|\/opt\/|\/var\/www|c:\\|d:\\|windows\\|program files|\/etc\/|\/root\/)(?:\/|\\)?[\w\-\.]+/i,
    field: 'response',
    severity: 'high',
    score: 78,
    category: 'data-leakage',
    description: 'Absolute file path disclosed in response',
    recommendation: 'Avoid exposing system paths in error messages'
  },
  {
    id: 'data-email-disclosure',
    name: 'Data Leakage - Email Address Exposure',
    pattern: /\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b/,
    field: 'response',
    severity: 'medium',
    score: 60,
    category: 'data-leakage',
    description: 'Email addresses exposed in response',
    recommendation: 'Redact email addresses in user-facing responses'
  },
  {
    id: 'data-credit-card',
    name: 'Data Leakage - Credit Card Numbers',
    pattern: /\b(?:\d{4}[\s\-]?){3}\d{4}\b|4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}/,
    field: 'response',
    severity: 'critical',
    score: 95,
    category: 'data-leakage',
    description: 'Credit card numbers in response',
    recommendation: 'Never expose full credit card data'
  },
  {
    id: 'data-ssn-disclosure',
    name: 'Data Leakage - Social Security Numbers',
    pattern: /\b\d{3}-\d{2}-\d{4}\b|\b\d{9}\b(?=\D|$)/,
    field: 'response',
    severity: 'critical',
    score: 93,
    category: 'data-leakage',
    description: 'Social Security number exposure',
    recommendation: 'Encrypt and protect SSN data'
  },
  {
    id: 'data-private-key',
    name: 'Data Leakage - Private Key Exposure',
    pattern: /(-----BEGIN\s+(PRIVATE|RSA|DSA|EC)\s+KEY|-----BEGIN\s+PRIVATE\s+KEY|\{-----BEGIN|ssh-rsa|ssh-ed25519)/i,
    field: 'response',
    severity: 'critical',
    score: 96,
    category: 'data-leakage',
    description: 'Private cryptographic keys in response',
    recommendation: 'Never expose private keys'
  },
  {
    id: 'data-api-key-disclosure',
    name: 'Data Leakage - API Key Exposure',
    pattern: /(api[_-]?key|apikey|api_secret|secret_key|access_token|bearer|authorization)[\s:=]*[a-zA-Z0-9\-_.]{20,}/i,
    field: 'response',
    severity: 'critical',
    score: 94,
    category: 'data-leakage',
    description: 'API keys or tokens exposed',
    recommendation: 'Mask API keys in responses'
  },
  {
    id: 'data-database-credentials',
    name: 'Data Leakage - Database Credentials',
    pattern: /(db_?user|db_?pass|database_?url|connection_?string|mysql_user|mysql_pass|postgres_user|postgres_pass)[\s:=]*[^\s<>\\"']+[\s<>\\"']/i,
    field: 'response',
    severity: 'critical',
    score: 94,
    category: 'data-leakage',
    description: 'Database credentials in response',
    recommendation: 'Never expose database credentials'
  },
  {
    id: 'data-directory-listing',
    name: 'Data Leakage - Directory Listing',
    pattern: /<title>[^<]*index of|<h1>[^<]*directory listing|<a\s+href="[^"]*"\s*>[a-zA-Z0-9_.-]+\/(?:<\/a>)?/i,
    field: 'response',
    severity: 'medium',
    score: 70,
    category: 'data-leakage',
    description: 'Unprotected directory listing',
    recommendation: 'Disable directory indexing'
  },
  {
    id: 'data-config-exposure',
    name: 'Data Leakage - Configuration File Exposure',
    pattern: /(web\.config|\.env|config\.php|settings\.py|appconfig\.json|database\.yml|credentials\.json|\.aws\/|\.ssh\/)/i,
    field: 'response',
    severity: 'critical',
    score: 92,
    category: 'data-leakage',
    description: 'Configuration files in response',
    recommendation: 'Exclude config files from web access'
  },
  {
    id: 'data-source-code-exposure',
    name: 'Data Leakage - Source Code Exposure',
    pattern: /(php source code|view source|\.php:|<?php|import\s+|from\s+\w+\s+import|def\s+\w+\(|class\s+\w+[\s{:])[\s\S]{0,500}(?:copyright|author|license|\$_[A-Z]+|\bfunction\b)/i,
    field: 'response',
    severity: 'high',
    score: 85,
    category: 'data-leakage',
    description: 'Source code exposed in response',
    recommendation: 'Prevent source code disclosure via error messages'
  },
  {
    id: 'data-ip-address-disclosure',
    name: 'Data Leakage - Internal IP Address',
    pattern: /(internal|server|local)[\s:]*(?:ip|address|addr)[\s:=]*(\d{1,3}\.){3}\d{1,3}|from\s*(?:\d{1,3}\.){3}\d{1,3}|connected.*(?:\d{1,3}\.){3}\d{1,3}/i,
    field: 'response',
    severity: 'medium',
    score: 68,
    category: 'data-leakage',
    description: 'Internal IP addresses disclosed',
    recommendation: 'Don\'t expose internal IPs'
  },
  {
    id: 'data-hostname-disclosure',
    name: 'Data Leakage - Hostname Disclosure',
    pattern: /(?:hostname|server|host)[\s:=]*[\w-]+\.(?:local|internal|corp|prod|dev|staging|test)/i,
    field: 'response',
    severity: 'medium',
    score: 65,
    category: 'data-leakage',
    description: 'Sensitive hostnames disclosed',
    recommendation: 'Mask or avoid exposing internal hostnames'
  },
  {
    id: 'data-session-id-exposure',
    name: 'Data Leakage - Session ID in URL',
    pattern: /jsessionid|phpsessid|aspsessionid|session_id|sessionid|sid=[\da-zA-Z]+/i,
    field: 'response',
    severity: 'high',
    score: 80,
    category: 'data-leakage',
    description: 'Session identifiers in URL or response',
    recommendation: 'Use secure, httponly session cookies only'
  },
  {
    id: 'data-auth-header-exposure',
    name: 'Data Leakage - Authorization Header Info',
    pattern: /(authorization|bearer|basic)\s+[a-zA-Z0-9\+\/=]{20,}|www-authenticate/i,
    field: 'response',
    severity: 'high',
    score: 82,
    category: 'data-leakage',
    description: 'Authentication credentials in response',
    recommendation: 'Don\'t expose auth tokens in responses'
  },
  {
    id: 'data-backup-file-exposure',
    name: 'Data Leakage - Backup File Exposure',
    pattern: /\.(bak|backup|old|orig|tmp|test|copy|swp|swo|~|\.1|\.2|\.3|\.gz|\.zip|\.tar)[\s\/<>\\"']/i,
    field: 'response',
    severity: 'high',
    score: 79,
    category: 'data-leakage',
    description: 'Backup or temporary files exposed',
    recommendation: 'Remove backup files from web root'
  },
  {
    id: 'data-debug-page',
    name: 'Data Leakage - Debug/Error Page',
    pattern: /(debug|development|staging|test)[\s:]*(?:mode|environment|enabled|true)|error occurred|exception details|traceback|debug info/i,
    field: 'response',
    severity: 'high',
    score: 76,
    category: 'data-leakage',
    description: 'Debug or error page exposed',
    recommendation: 'Use custom error pages in production'
  },
  {
    id: 'data-database-schema',
    name: 'Data Leakage - Database Schema Info',
    pattern: /(table|column|index|constraint|trigger|procedure|view|schema)[\s:]+(?:name|type|size)|information_schema|mysql\.user|pg_catalog/i,
    field: 'response',
    severity: 'high',
    score: 77,
    category: 'data-leakage',
    description: 'Database schema information exposed',
    recommendation: 'Limit database introspection'
  },
  {
    id: 'data-pii-name',
    name: 'Data Leakage - Personal Information (Names)',
    pattern: /(?:first_?name|last_?name|full_?name|name)[\s:=]*[A-Z][a-z]+[\s]+[A-Z][a-z]+/,
    field: 'response',
    severity: 'medium',
    score: 62,
    category: 'data-leakage',
    description: 'Personal names exposed in response',
    recommendation: 'Minimize PII in responses'
  },
  {
    id: 'data-phone-number',
    name: 'Data Leakage - Phone Number Exposure',
    pattern: /\b(?:\+?1[-.\s]?)?\(?[2-9]\d{2}\)?[-.\s]?[2-9]\d{2}[-.\s]?\d{4}\b|phone[\s:=]*\+?[\d\s\-().]{10,15}/i,
    field: 'response',
    severity: 'medium',
    score: 63,
    category: 'data-leakage',
    description: 'Phone numbers exposed',
    recommendation: 'Redact phone numbers'
  },
  {
    id: 'data-bank-account',
    name: 'Data Leakage - Bank Account Numbers',
    pattern: /(?:account|iban|routing|bank\s+account)[\s:=]*[\d\-]{10,20}|iban[\s:]*[A-Z]{2}\d{2}[A-Z0-9]{1,30}/i,
    field: 'response',
    severity: 'critical',
    score: 93,
    category: 'data-leakage',
    description: 'Bank account numbers exposed',
    recommendation: 'Never expose account numbers'
  },
  {
    id: 'data-timestamp-precision',
    name: 'Data Leakage - Excessive Timestamp Precision',
    pattern: /\d{4}-\d{2}-\d{2}\s*[T\s]\d{2}:\d{2}:\d{2}\.\d{6,}/,
    field: 'response',
    severity: 'low',
    score: 40,
    category: 'data-leakage',
    description: 'Microsecond-precision timestamps (can aid attacks)',
    recommendation: 'Use second-level precision only'
  },
  {
    id: 'data-unicode-normalization',
    name: 'Data Leakage - Unicode/UTF-8 Encoding Tricks',
    pattern: /\\u[0-9a-fA-F]{4}|&#[0-9]+;|%[0-9a-fA-F]{2}.*(?:select|union|script|iframe)/i,
    field: 'response',
    severity: 'medium',
    score: 61,
    category: 'data-leakage',
    description: 'Encoded payloads in response',
    recommendation: 'Normalize and validate responses'
  },
  {
    id: 'data-serialized-objects',
    name: 'Data Leakage - Serialized Objects',
    pattern: /(java\.io\.serializable|serialVersionUID|readObject|writeObject|base64|pickle|serialized)/i,
    field: 'response',
    severity: 'high',
    score: 78,
    category: 'data-leakage',
    description: 'Serialized objects in response',
    recommendation: 'Avoid returning serialized objects'
  },
  {
    id: 'data-null-byte-injection',
    name: 'Data Leakage - Null Byte Injection',
    pattern: /%00|\\x00|\\0|%0/,
    field: 'response',
    severity: 'medium',
    score: 64,
    category: 'data-leakage',
    description: 'Null byte characters in response',
    recommendation: 'Strip null bytes from responses'
  }
];
