// Remote Code Execution Rules (ModSecurity CRS 932)
export const RCE_RULES = [
  {
    id: 'rce-shell-commands',
    name: 'RCE - Shell Command Execution',
    pattern: /\b(bash|sh|cmd|powershell|exec|system|passthru|eval|assert|compile)\s*\(/i,
    field: 'request',
    severity: 'critical',
    score: 98,
    category: 'rce',
    description: 'Shell command execution functions detected',
    recommendation: 'Disable dangerous functions, use allowlist for commands'
  },
  {
    id: 'rce-pipe-operators',
    name: 'RCE - Pipe Operators',
    pattern: /[|&;`$()><\n].*\b(cat|ls|rm|mv|cp|chmod|chown|whoami|id|uname|nc|ncat|telnet)\b/i,
    field: 'request',
    severity: 'critical',
    score: 95,
    category: 'rce',
    description: 'Shell pipe/redirect operators with system commands',
    recommendation: 'Block shell metacharacters and chaining'
  },
  {
    id: 'rce-reverse-shell',
    name: 'RCE - Reverse Shell Patterns',
    pattern: /\/bin\/bash|\/bin\/sh|\/bin\/dash|cmd\.exe|powershell\.exe|nc\s+-[a-z]*e|bash\s+-i|sh\s+-i/i,
    field: 'request',
    severity: 'critical',
    score: 96,
    category: 'rce',
    description: 'Reverse shell or interactive shell execution',
    recommendation: 'Restrict shell access and outbound connections'
  },
  {
    id: 'rce-code-injection',
    name: 'RCE - Code Injection',
    pattern: /eval\s*\(|exec\s*\(|system\s*\(|assert\s*\(|create_function|preg_replace\s*\/[a-z]*e/i,
    field: 'request',
    severity: 'critical',
    score: 94,
    category: 'rce',
    description: 'Code injection via eval, exec, or similar functions',
    recommendation: 'Never use user input with eval/exec functions'
  },
  {
    id: 'rce-environment-variables',
    name: 'RCE - Environment Variable Injection',
    pattern: /LD_PRELOAD|LD_LIBRARY_PATH|DYLD_INSERT_LIBRARIES|PATH=|PYTHONPATH=|CLASSPATH=/i,
    field: 'request',
    severity: 'high',
    score: 85,
    category: 'rce',
    description: 'Environment variable manipulation for code execution',
    recommendation: 'Sanitize environment variables, use isolated environments'
  },
  {
    id: 'rce-process-execution',
    name: 'RCE - Process Execution',
    pattern: /Runtime\.exec|ProcessBuilder|ProcessImpl|spawn|fork|popen|subprocess\.call/i,
    field: 'request',
    severity: 'critical',
    score: 92,
    category: 'rce',
    description: 'Language-level process execution functions',
    recommendation: 'Restrict process execution, use safe APIs only'
  },
  {
    id: 'rce-wildcards-globbing',
    name: 'RCE - Glob/Wildcard Expansion',
    pattern: /\$\{.*?\}|\$\(.*?\)|`.*?`|\*\.\*|[\[\]{}]/,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'rce',
    description: 'Command substitution or glob expansion patterns',
    recommendation: 'Quote parameters, disable shell expansion'
  },
  {
    id: 'rce-directory-traversal-execution',
    name: 'RCE - Directory Traversal to Execute',
    pattern: /\.\.\/.*\.(sh|exe|com|bat|cmd|bin|elf|o|so)|\.\/\.\.\/.*\.(sh|exe|com|bat|cmd)/i,
    field: 'request',
    severity: 'high',
    score: 88,
    category: 'rce',
    description: 'Directory traversal combined with command execution',
    recommendation: 'Validate file paths, restrict executable locations'
  },
  {
    id: 'rce-input-output-redirection',
    name: 'RCE - Input/Output Redirection',
    pattern: />\s*\/dev\/\w+|<\s*\/proc\/|[\d+]>\s*&[\d+]|[\d+]<>\s*\/dev\//,
    field: 'request',
    severity: 'high',
    score: 82,
    category: 'rce',
    description: 'I/O redirection to special files',
    recommendation: 'Block redirection to /dev/ and /proc/'
  },
  {
    id: 'rce-dangerous-imports',
    name: 'RCE - Dangerous Module Imports',
    pattern: /require\s*\(\s*['"`].*\$|import\s+.*\${.*}|__import__\s*\(\s*['"`]\$/i,
    field: 'request',
    severity: 'critical',
    score: 91,
    category: 'rce',
    description: 'Dynamic module/file imports with user input',
    recommendation: 'Use static imports only, validate module names'
  },
  {
    id: 'rce-command-substitution',
    name: 'RCE - Command Substitution $()',
    pattern: /\$\([^)]*(?:cat|ls|rm|wget|curl|bash|sh|id|whoami)/i,
    field: 'request',
    severity: 'critical',
    score: 96,
    category: 'rce',
    description: 'Command substitution with system commands',
    recommendation: 'Block $(command) substitution'
  },
  {
    id: 'rce-backtick-substitution',
    name: 'RCE - Backtick Command Substitution',
    pattern: /`[^`]*(?:cat|ls|rm|wget|curl|bash|sh|id|whoami)/i,
    field: 'request',
    severity: 'critical',
    score: 95,
    category: 'rce',
    description: 'Backtick command substitution',
    recommendation: 'Strip backticks from input'
  },
  {
    id: 'rce-unicode-bypass',
    name: 'RCE - Unicode/UTF-8 Command Bypass',
    pattern: /\\x2f|\\x3b|\\x7c|%2f|%3b|%7c|%24\(|%60/i,
    field: 'request',
    severity: 'high',
    score: 82,
    category: 'rce',
    description: 'Encoded shell metacharacters',
    recommendation: 'Decode and normalize input before validation'
  },
  {
    id: 'rce-hex-encoding-bypass',
    name: 'RCE - Hex Encoding Command Bypass',
    pattern: /\\x[0-9a-fA-F]{2}.*(?:exec|eval|system|bash)|0x(?:[0-9a-fA-F]{2})+/i,
    field: 'request',
    severity: 'high',
    score: 81,
    category: 'rce',
    description: 'Hex-encoded RCE payloads',
    recommendation: 'Decode all inputs before pattern matching'
  },
  {
    id: 'rce-octal-encoding',
    name: 'RCE - Octal Encoding Bypass',
    pattern: /\\[0-7]{3}.*(?:bash|sh|exec|eval)|[0-7]{3,4}.*(?:bash|sh)/i,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'rce',
    description: 'Octal-encoded command bypasses',
    recommendation: 'Normalize octal sequences'
  },
  {
    id: 'rce-iis-shortname-rce',
    name: 'RCE - IIS Short Filename (8.3) RCE',
    pattern: /\.asp~\d|\.aspx~\d|\.jsp~\d|\*\.asp[\s?]|iis|shortname|~1~2/i,
    field: 'request',
    severity: 'high',
    score: 83,
    category: 'rce',
    description: 'IIS 8.3 short filename disclosure for RCE',
    recommendation: 'Disable 8.3 naming on IIS'
  },
  {
    id: 'rce-polyglot-files',
    name: 'RCE - Polyglot File Uploads',
    pattern: /GIF8|GIF89|GIF87|JFIF|PNG|ZIP|php|jsp|asp|jspx|aspx/i,
    field: 'file_content_header',
    severity: 'high',
    score: 84,
    category: 'rce',
    description: 'Polyglot files combining image+code',
    recommendation: 'Validate file types strictly'
  },
  {
    id: 'rce-null-byte-execution',
    name: 'RCE - Null Byte Injection',
    pattern: /\.php%00|\.asp%00|\.jsp%00|%00\.jpg|%00\.gif|\.php\x00/i,
    field: 'request',
    severity: 'high',
    score: 82,
    category: 'rce',
    description: 'Null byte in filename for extension bypass',
    recommendation: 'Strip and validate null bytes'
  },
  {
    id: 'rce-double-extension',
    name: 'RCE - Double Extension Upload',
    pattern: /\.php\.jpg|\.php\.png|\.php\.gif|\.asp\.jpg|\.jsp\.gif|\.php\.txt|\.php\.pdf/i,
    field: 'request',
    severity: 'high',
    score: 81,
    category: 'rce',
    description: 'Double extension file upload bypass',
    recommendation: 'Validate only final extension'
  },
  {
    id: 'rce-case-insensitive-bypass',
    name: 'RCE - Case Sensitivity Bypass',
    pattern: /\.pHp|\.AsP|\.jSp|\.Php5|\.phtml|\.shtml|\.shtm|\.sh\s/i,
    field: 'request',
    severity: 'medium',
    score: 70,
    category: 'rce',
    description: 'Mixed case extension bypass',
    recommendation: 'Use case-insensitive validation'
  },
  {
    id: 'rce-alternate-stream-ads',
    name: 'RCE - NTFS Alternate Data Streams',
    pattern: /\.jpg::|\\.jpg:|\.:jpg:|file\.txt:jpg|stream\s*::|zone\.identifier/i,
    field: 'request',
    severity: 'high',
    score: 83,
    category: 'rce',
    description: 'NTFS alternate data stream abuse',
    recommendation: 'Filter NTFS stream syntax'
  },
  {
    id: 'rce-asp-dot-dot',
    name: 'RCE - ASP Dot-Dot Traversal',
    pattern: /\.\.\..*asp|asp\.\.\.|\.\.\/\.\.\/.*asp|aspx\.\.\./i,
    field: 'request',
    severity: 'high',
    score: 79,
    category: 'rce',
    description: 'ASP dot-dot directory traversal',
    recommendation: 'Normalize paths properly'
  },
  {
    id: 'rce-parser-confusion',
    name: 'RCE - Parser Confusion Attacks',
    pattern: /\.php5|\.phtml|\.phar|\.phps|\.php3|\.php4|\.php7|\.pht|\.phpt|\.pgif|\.shtml/i,
    field: 'request',
    severity: 'high',
    score: 82,
    category: 'rce',
    description: 'Parser confusion via alternate extensions',
    recommendation: 'Whitelist allowed extensions only'
  },
  {
    id: 'rce-htaccess-upload',
    name: 'RCE - .htaccess Upload',
    pattern: /\.htaccess|\.htpasswd|\.web\.config|\.aspx_client|\.user\.js/i,
    field: 'request',
    severity: 'critical',
    score: 94,
    category: 'rce',
    description: 'Configuration file upload for RCE',
    recommendation: 'Block upload of sensitive files'
  },
  {
    id: 'rce-symlink-exploitation',
    name: 'RCE - Symlink/Hardlink Exploitation',
    pattern: /ln\s+-s|symlink|hardlink|mknod|mkfifo|ln\s+-h|readlink/i,
    field: 'request',
    severity: 'high',
    score: 81,
    category: 'rce',
    description: 'Symlink creation for privilege escalation',
    recommendation: 'Restrict symlink operations'
  },
  {
    id: 'rce-race-condition',
    name: 'RCE - Race Condition/TOCTOU',
    pattern: /tmp\/|\/var\/tmp|tempfile|mktemp|temp.*dir|race|toctou/i,
    field: 'request',
    severity: 'medium',
    score: 72,
    category: 'rce',
    description: 'Time-of-check/time-of-use race conditions',
    recommendation: 'Use atomic operations, secure temp files'
  },
  {
    id: 'rce-perl-open',
    name: 'RCE - Perl Open/System Injection',
    pattern: /open\s*\(\s*['"`]\||\bopen\s+my|system\s*\(/i,
    field: 'request',
    severity: 'critical',
    score: 93,
    category: 'rce',
    description: 'Perl system() or piped open() execution',
    recommendation: 'Avoid bareword filehandles'
  },
  {
    id: 'rce-php-assert-code',
    name: 'RCE - PHP assert() Code Execution',
    pattern: /assert\s*\([^)]*\$|assert\s*\(\s*['"`].*(?:eval|exec|system|shell_exec)/i,
    field: 'request',
    severity: 'critical',
    score: 92,
    category: 'rce',
    description: 'PHP assert() with code evaluation',
    recommendation: 'Never use assert() with user input'
  },
  {
    id: 'rce-preg-replace-code',
    name: 'RCE - preg_replace /e Modifier',
    pattern: /preg_replace\s*\(.*\/[a-z]*e|preg_replace\s*\(.*['\"]e['\"]/i,
    field: 'request',
    severity: 'critical',
    score: 93,
    category: 'rce',
    description: 'PHP preg_replace() with /e modifier',
    recommendation: 'Use preg_replace_callback() instead'
  },
  {
    id: 'rce-create-function-eval',
    name: 'RCE - create_function() RCE',
    pattern: /create_function\s*\(|create_function\s*\(['\"][^'\"]*\$|eval\s*\(\s*\$_(GET|POST|COOKIE)/i,
    field: 'request',
    severity: 'critical',
    score: 91,
    category: 'rce',
    description: 'create_function() for anonymous function RCE',
    recommendation: 'Use closures/lambdas, never with user input'
  },
  {
    id: 'rce-variable-variables',
    name: 'RCE - PHP Variable Variables',
    pattern: /\$\$\w+|$$\(|${.*}.*\$/,
    field: 'request',
    severity: 'high',
    score: 85,
    category: 'rce',
    description: 'PHP variable variables ${} syntax',
    recommendation: 'Avoid variable variables with user input'
  },
  {
    id: 'rce-extract-import-vars',
    name: 'RCE - extract()/import_request_variables()',
    pattern: /extract\s*\(|import_request_variables|parse_str\s*\(/i,
    field: 'request',
    severity: 'high',
    score: 84,
    category: 'rce',
    description: 'PHP extract() function for variable injection',
    recommendation: 'Avoid extract(), use explicit assignment'
  },
  {
    id: 'rce-mysql-exec',
    name: 'RCE - MySQL INTO OUTFILE/LOAD DATA',
    pattern: /INTO\s+(OUTFILE|DUMPFILE)|LOAD_FILE|LOAD\s+DATA.*INFILE|INTO\s+OUTFILE.*shell/i,
    field: 'request',
    severity: 'critical',
    score: 94,
    category: 'rce',
    description: 'MySQL file write for RCE',
    recommendation: 'Restrict FILE privilege'
  },
  {
    id: 'rce-udf-exploitation',
    name: 'RCE - User Defined Function (UDF) Exploitation',
    pattern: /sys_exec|sys_eval|udf\.dll|lib_mysqludf|create\s+function|into.*\.so|into.*\.dll/i,
    field: 'request',
    severity: 'critical',
    score: 93,
    category: 'rce',
    description: 'Database UDF for shell execution',
    recommendation: 'Restrict UDF creation'
  },
  {
    id: 'rce-mongodb-injection',
    name: 'RCE - MongoDB Code Injection',
    pattern: /\$where[\s:]*|mapReduce|function\s*\(\s*\)|eval\s*\(|function\(\)\s*\{[\s\S]*(?:exec|spawn)/i,
    field: 'request',
    severity: 'critical',
    score: 92,
    category: 'rce',
    description: 'MongoDB $where operator code injection',
    recommendation: 'Avoid $where, use strict queries'
  },
  {
    id: 'rce-nosql-regex-dos',
    name: 'RCE - NoSQL Regex DoS to RCE',
    pattern: /\$regex[\s:]*.*\(|\/.*\/[\w]{100,}|pattern.*[*+{]{2,}/,
    field: 'request',
    severity: 'high',
    score: 86,
    category: 'rce',
    description: 'NoSQL regex patterns for DoS/RCE',
    recommendation: 'Validate regex complexity'
  },
  {
    id: 'rce-cgi-bin-exploitation',
    name: 'RCE - CGI Bin Exploitation',
    pattern: /cgi-bin|\.cgi|\.pl|sendmail|index\.cgi|status\.cgi|test\.cgi/i,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'rce',
    description: 'CGI script exploitation',
    recommendation: 'Secure CGI scripts, use modern frameworks'
  },
  {
    id: 'rce-imagetragick',
    name: 'RCE - ImageMagick (ImageTragick)',
    pattern: /imagick|convert|mogrify|identify|composite|delegate|popen|powershell|cmd\.exe/i,
    field: 'request',
    severity: 'high',
    score: 83,
    category: 'rce',
    description: 'ImageMagick RCE via delegate commands',
    recommendation: 'Update ImageMagick, disable delegates'
  },
  {
    id: 'rce-ghostscript',
    name: 'RCE - Ghostscript PDF Injection',
    pattern: /ghostscript|gs\.exe|gswin64|pdf.*exec|currentdevice|stdin|stdout/i,
    field: 'request',
    severity: 'high',
    score: 82,
    category: 'rce',
    description: 'Ghostscript PostScript RCE',
    recommendation: 'Update Ghostscript, disable -dSAFER'
  },
  {
    id: 'rce-ffmpeg-injection',
    name: 'RCE - FFmpeg Command Injection',
    pattern: /ffmpeg|ffprobe|avconv|filter_complex|custom_filter|pipe:/i,
    field: 'request',
    severity: 'high',
    score: 81,
    category: 'rce',
    description: 'FFmpeg filter/codec injection',
    recommendation: 'Use whitelist, quote all parameters'
  },
  {
    id: 'rce-latex-injection',
    name: 'RCE - LaTeX/TeX Command Injection',
    pattern: /\\immediate\\write18|\\def\\x|\\expandafter|pdflatex|xetex|luatex|\\input|\\include/i,
    field: 'request',
    severity: 'critical',
    score: 94,
    category: 'rce',
    description: 'LaTeX/TeX shell escape RCE',
    recommendation: 'Disable shell escape, sandbox LaTeX'
  },
  {
    id: 'rce-graphviz-injection',
    name: 'RCE - Graphviz DOT Injection',
    pattern: /digraph|graph\s*{|node|edge|shellcommand|system|exec/i,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'rce',
    description: 'Graphviz DOT language injection',
    recommendation: 'Validate DOT syntax, disable shell'
  },
  {
    id: 'rce-aspx-viewstate',
    name: 'RCE - ASP.NET ViewState Deserialization',
    pattern: /viewstate|__viewstate|objectstatefromstring|deserialize.*viewstate/i,
    field: 'request',
    severity: 'critical',
    score: 93,
    category: 'rce',
    description: 'ASP.NET ViewState gadget chains',
    recommendation: 'Enable ViewState MAC, use ysoserial prevention'
  },
  {
    id: 'rce-source-code-comment',
    name: 'RCE - Source Code in Comments',
    pattern: /<!--[\s\S]*(?:exec|system|bash|shell_exec|eval)[\s\S]*-->|\/\*[\s\S]*(?:exec|system)[\s\S]*\*\//i,
    field: 'response',
    severity: 'medium',
    score: 75,
    category: 'rce',
    description: 'Executable code in HTML comments',
    recommendation: 'Never include code in comments'
  }
];
