export const RECONNAISSANCE_RULES = [
  {id:'scanner-detection',name:'Security Scanner Detection',pattern:/(sqlmap|nikto|nessus|burp|acunetix|netsparker|owasp|zap|w3af|whatweb|masscan|nmap)/i,field:'headers',severity:'medium',score:60,category:'reconnaissance',description:'Known security scanner user agent',recommendation:'Consider blocking automated tools'},
  {id:'scanner-dirbuster',name:'Scanner - DirBuster/GoBuster',pattern:/(dirbuster|gobuster|feroxbuster|dirb|wfuzz|ffuf)/i,field:'headers',severity:'medium',score:58,category:'reconnaissance',description:'Directory enumeration tool detected',recommendation:'Block directory scanners'},
  {id:'scanner-metasploit',name:'Scanner - Metasploit Framework',pattern:/(metasploit|msfvenom|msfconsole|rapid7)/i,field:'headers',severity:'medium',score:62,category:'reconnaissance',description:'Metasploit exploitation framework',recommendation:'Monitor for exploitation attempts'},
  {id:'scanner-qualys',name:'Scanner - Qualys',pattern:/(qualys|qualysguard|qualysassets)/i,field:'headers',severity:'medium',score:59,category:'reconnaissance',description:'Qualys vulnerability scanner',recommendation:'Block or rate limit'},
  {id:'scanner-openvas',name:'Scanner - OpenVAS',pattern:/(openvas|greenbone)/i,field:'headers',severity:'medium',score:57,category:'reconnaissance',description:'OpenVAS vulnerability scanner',recommendation:'Monitor scanner activity'},
  {id:'scanner-tenable',name:'Scanner - Tenable',pattern:/(tenable|nessusagent|lumin)/i,field:'headers',severity:'medium',score:61,category:'reconnaissance',description:'Tenable Nessus agent',recommendation:'Restrict access'},
  {id:'scanner-rapid7',name:'Scanner - Rapid7 InsightVM',pattern:/(rapid7|insightvm|nexpose)/i,field:'headers',severity:'medium',score:60,category:'reconnaissance',description:'Rapid7 InsightVM scanner',recommendation:'Monitor vulnerability scans'},
  {id:'scanner-checkmarx',name:'Scanner - Checkmarx SAST',pattern:/(checkmarx|cxscan)/i,field:'headers',severity:'low',score:40,category:'reconnaissance',description:'Checkmarx SAST scanner (internal)',recommendation:'Whitelist internal scanners'},
  {id:'scanner-tools',name:'Scanner - Common Penetration Tools',pattern:/(nmap|hydra|hashcat|john|hashdeep|cain|abel|wireshark|tcpdump|metasploit)/i,field:'headers',severity:'medium',score:62,category:'reconnaissance',description:'Common penetration testing tools',recommendation:'Block or monitor'},
  {id:'scanner-content-discovery',name:'Scanner - Content Discovery Tools',pattern:/(dirsearch|cmsmap|joomlascan|wordpress-scanner|droopscan|drupal-enum)/i,field:'headers',severity:'medium',score:58,category:'reconnaissance',description:'CMS/content enumeration tools',recommendation:'Block automated enumeration'},
  {id:'scanner-api-fuzzer',name:'Scanner - API Fuzzing Tools',pattern:/(swagger-ui|api-fuzzer|postman-runtime|insomnia|burp|graphql-voyager)/i,field:'headers',severity:'medium',score:56,category:'reconnaissance',description:'API testing and fuzzing tools',recommendation:'Monitor API reconnaissance'},
  {id:'scanner-bot-user-agent',name:'Scanner - Suspicious Bot User Agent',pattern:/bot|crawler|scanner|spider|scraper|monitor|crawler|curl|wget|python-requests|urllib|httplib/i,field:'headers',severity:'low',score:35,category:'reconnaissance',description:'Generic bot or crawler detection',recommendation:'Implement rate limiting for bots'},
  {id:'scanner-custom-headers',name:'Scanner - Custom/Suspicious Headers',pattern:/(x-scanner|x-tool|x-test|x-debug|x-original-url|x-rewrite-url|x-forwarded|x-client-ip)/i,field:'headers',severity:'medium',score:55,category:'reconnaissance',description:'Custom headers indicating scanner/proxy',recommendation:'Monitor suspicious headers'},
  {id:'scanner-vulnerability-params',name:'Scanner - Vulnerability Test Parameters',pattern:/(union\s+select|sleep\(|benchmark\(|version\(\)|information_schema|admin.*password|test.*admin)/i,field:'query',severity:'high',score:75,category:'reconnaissance',description:'Common vulnerability testing parameters',recommendation:'Flag as scanning activity'},
  {id:'scanner-version-probe',name:'Scanner - Version/Info Disclosure Probes',pattern:/(version|info|debug|env|config|php_info|server.*version|banner)/i,field:'query',severity:'medium',score:50,category:'reconnaissance',description:'Information disclosure probes',recommendation:'Don\'t expose system info'}
];
