// XSS Rules
export const XSS_RULES = [
  {
    id: 'xss-script',
    name: 'XSS - Script Tag',
    pattern: /<script[^>]*>[\s\S]*?<\/script>/i,
    field: 'request',
    severity: 'critical',
    score: 90,
    category: 'xss',
    description: 'Classic script tag XSS attack',
    recommendation: 'Encode all output and use CSP headers'
  },
  {
    id: 'xss-event',
    name: 'XSS - Event Handler',
    pattern: /\bon(load|error|click|mouse|focus|blur|submit|change|key|touch|drag|drop|copy|paste|cut|select|scroll|resize|unload|beforeunload)\s*=/i,
    field: 'request',
    severity: 'high',
    score: 85,
    category: 'xss',
    description: 'XSS via HTML event handler attributes',
    recommendation: 'Strip event handlers from user input'
  },
  {
    id: 'xss-javascript',
    name: 'XSS - JavaScript Protocol',
    pattern: /javascript\s*:/i,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'xss',
    description: 'JavaScript protocol handler in URL/attribute',
    recommendation: 'Validate and whitelist URL protocols'
  },
  {
    id: 'xss-data',
    name: 'XSS - Data URI',
    pattern: /data\s*:\s*(text\/html|application\/javascript)/i,
    field: 'request',
    severity: 'high',
    score: 75,
    category: 'xss',
    description: 'Data URI with executable content type',
    recommendation: 'Block or validate data URIs'
  },
  {
    id: 'xss-svg',
    name: 'XSS - SVG Payload',
    pattern: /<svg[^>]*\son\w+\s*=/i,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'xss',
    description: 'XSS through SVG element with event handlers',
    recommendation: 'Sanitize SVG content or block SVG uploads'
  },
  {
    id: 'xss-img',
    name: 'XSS - Image Tag Abuse',
    pattern: /<img[^>]+\s(on\w+|src\s*=\s*['"]?javascript)/i,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'xss',
    description: 'XSS via img tag event handlers or javascript src',
    recommendation: 'Validate image sources and strip event handlers'
  },
  {
    id: 'xss-encoded',
    name: 'XSS - Encoded Payload',
    pattern: /(%3C|&#x3c;|&#60;).*?(script|on\w+=)/i,
    field: 'request',
    severity: 'high',
    score: 75,
    category: 'xss',
    description: 'URL or HTML encoded XSS attempt',
    recommendation: 'Decode and validate input before processing'
  },
  {
    id: 'xss-template',
    name: 'XSS - Template Injection',
    pattern: /(\{\{|\$\{|\<%=?|\{%)/,
    field: 'request',
    severity: 'medium',
    score: 55,
    category: 'xss',
    description: 'Potential template injection syntax',
    recommendation: 'Escape template delimiters in user input'
  },
  {
    id: 'xss-html-tags',
    name: 'XSS - HTML Tags',
    pattern: /<(iframe|object|embed|applet|meta|link|style|base|form)\b[^>]*>/i,
    field: 'request',
    severity: 'high',
    score: 85,
    category: 'xss',
    description: 'Dangerous HTML tags (iframe, object, embed, etc.)',
    recommendation: 'Remove or sanitize potentially dangerous HTML tags'
  },
  {
    id: 'xss-protocol-handlers',
    name: 'XSS - Protocol Handlers',
    pattern: /(vbscript|about|data|jar|mocha|mhtml):/i,
    field: 'request',
    severity: 'high',
    score: 82,
    category: 'xss',
    description: 'Alternative protocol handlers for XSS',
    recommendation: 'Whitelist only safe protocols (http, https, ftp)'
  },
  {
    id: 'xss-entity-encoding',
    name: 'XSS - Entity Encoding Bypass',
    pattern: /&#\d+;|&#x[0-9a-fA-F]+;|%[0-9a-fA-F]{2}|\\x[0-9a-fA-F]{2}/,
    field: 'request',
    severity: 'medium',
    score: 70,
    category: 'xss',
    description: 'Entity/URL encoded XSS payloads',
    recommendation: 'Decode entities before validation'
  },
  {
    id: 'xss-css-injection',
    name: 'XSS - CSS Injection',
    pattern: /<style[^>]*>[\s\S]*?<\/style>|style\s*=\s*"[^"]*expression|behavior\s*:|binding\s*:/i,
    field: 'request',
    severity: 'high',
    score: 80,
    category: 'xss',
    description: 'CSS-based XSS attacks',
    recommendation: 'Sanitize style attributes and <style> tags'
  },
  {
    id: 'xss-svg-filter',
    name: 'XSS - SVG Filter Effects',
    pattern: /<filter[^>]*>[\s\S]*?<\/filter>|<animate[^>]*>|<set\b[^>]*>/i,
    field: 'request',
    severity: 'high',
    score: 78,
    category: 'xss',
    description: 'SVG filter or animation elements for XSS',
    recommendation: 'Block dangerous SVG elements'
  },
  {
    id: 'xss-html5-attributes',
    name: 'XSS - HTML5 Dangerous Attributes',
    pattern: /\b(formaction|onfocus|onload|onmouseover|onmouseout|onmousemove|onmousedown|onmouseup|onkeydown|onkeyup|onkeypress)\s*=/i,
    field: 'request',
    severity: 'high',
    score: 83,
    category: 'xss',
    description: 'HTML5 event attributes for XSS',
    recommendation: 'Remove event attributes from all elements'
  },
  {
    id: 'xss-meta-refresh',
    name: 'XSS - Meta Refresh',
    pattern: /<meta[^>]+http-equiv\s*=\s*["']refresh["'][^>]*>/i,
    field: 'request',
    severity: 'medium',
    score: 65,
    category: 'xss',
    description: 'Meta refresh tag for redirect/injection',
    recommendation: 'Remove or sanitize meta refresh tags'
  },
  {
    id: 'xss-unicode-evasion',
    name: 'XSS - Unicode/UTF-8 Evasion',
    pattern: /\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8}|%u[0-9a-fA-F]{4}|&#x[0-9a-fA-F]{2,6};/,
    field: 'request',
    severity: 'high',
    score: 75,
    category: 'xss',
    description: 'Unicode encoding for XSS evasion',
    recommendation: 'Normalize and decode Unicode sequences'
  },
  {
    id: 'xss-form-action',
    name: 'XSS - Form Action Hijacking',
    pattern: /<form[^>]+action\s*=\s*["']?(?!https?:\/\/trusted-domain)(javascript:|data:|about:|\/{0,2}[^\/])/i,
    field: 'request',
    severity: 'high',
    score: 79,
    category: 'xss',
    description: 'Form action pointing to external or dangerous protocol',
    recommendation: 'Whitelist allowed form actions'
  },
  {
    id: 'xss-base64-polyglot',
    name: 'XSS - Base64/Polyglot Encoding',
    pattern: /data:text\/html;base64,|PHN2Z1|PGlmcmFtZQ==|PHNjcmlwdD4=/i,
    field: 'request',
    severity: 'high',
    score: 81,
    category: 'xss',
    description: 'Base64 encoded XSS payloads',
    recommendation: 'Decode and validate base64 content'
  },
  {
    id: 'xss-dom-innerhtml',
    name: 'XSS - DOM innerhtml Manipulation',
    pattern: /\.innerHTML\s*=|\.insertAdjacentHTML|document\.write\s*\(|outerHTML\s*=/i,
    field: 'request',
    severity: 'high',
    score: 84,
    category: 'xss',
    description: 'DOM-based XSS via innerHTML/write',
    recommendation: 'Use textContent, use DOMPurify for HTML'
  },
  {
    id: 'xss-dom-eval',
    name: 'XSS - DOM eval() Injection',
    pattern: /eval\s*\(|setTimeout\s*\(\s*['"`]|setInterval\s*\(\s*['"`]|Function\s*\(['"`]/i,
    field: 'request',
    severity: 'critical',
    score: 92,
    category: 'xss',
    description: 'eval() or Function() with user input',
    recommendation: 'Never use eval(), setTimeout/Interval with code strings'
  },
  {
    id: 'xss-dom-query-selector',
    name: 'XSS - querySelector XSS',
    pattern: /querySelector\s*\(['"]\s*<|querySelectorAll[\s\S]*?<(?:img|script|svg|iframe)/i,
    field: 'request',
    severity: 'high',
    score: 78,
    category: 'xss',
    description: 'HTML injection via querySelector',
    recommendation: 'Sanitize selector input'
  },
  {
    id: 'xss-attribute-injection',
    name: 'XSS - Attribute Injection',
    pattern: /"\s*\s(?:on\w+|href|src|data|style|poster)\s*=|'\s+on\w+\s*=|`\s+on\w+\s*=/i,
    field: 'request',
    severity: 'high',
    score: 82,
    category: 'xss',
    description: 'Breaking out of attributes with space',
    recommendation: 'Properly quote and escape attributes'
  },
  {
    id: 'xss-svg-onload',
    name: 'XSS - SVG with onload',
    pattern: /<svg[\s\S]*?onload\s*=/i,
    field: 'request',
    severity: 'critical',
    score: 88,
    category: 'xss',
    description: 'SVG element with onload handler',
    recommendation: 'Sanitize or block SVG uploads'
  },
  {
    id: 'xss-canvas-xss',
    name: 'XSS - Canvas/Blob Data URI',
    pattern: /canvas\.toDataURL|blob:|createObjectURL|createImageBitmap/i,
    field: 'request',
    severity: 'high',
    score: 76,
    category: 'xss',
    description: 'Canvas/Blob for data exfiltration',
    recommendation: 'Restrict data URL generation'
  },
  {
    id: 'xss-iframe-srcdoc',
    name: 'XSS - iframe srcdoc XSS',
    pattern: /srcdoc\s*=|<iframe[^>]+srcdoc/i,
    field: 'request',
    severity: 'critical',
    score: 89,
    category: 'xss',
    description: 'iframe srcdoc attribute for inline HTML',
    recommendation: 'Sanitize srcdoc attribute'
  },
  {
    id: 'xss-script-src-data',
    name: 'XSS - Script src=data: URI',
    pattern: /<script[^>]+src\s*=\s*["']?data:/i,
    field: 'request',
    severity: 'critical',
    score: 90,
    category: 'xss',
    description: 'Script tag with data URI',
    recommendation: 'Block data: scheme in script src'
  },
  {
    id: 'xss-link-rel-import',
    name: 'XSS - Link rel=import',
    pattern: /<link[^>]+rel\s*=\s*["']import["']/i,
    field: 'request',
    severity: 'high',
    score: 74,
    category: 'xss',
    description: 'HTML imports for XSS',
    recommendation: 'Disable HTML imports or sanitize'
  },
  {
    id: 'xss-object-data-xss',
    name: 'XSS - Object data Attribute',
    pattern: /<object[^>]+data\s*=|<embed[^>]+src\s*=/i,
    field: 'request',
    severity: 'high',
    score: 83,
    category: 'xss',
    description: 'Object/Embed tag XSS',
    recommendation: 'Remove or heavily sanitize object/embed'
  },
  {
    id: 'xss-video-poster',
    name: 'XSS - Video Poster XSS',
    pattern: /<video[^>]+poster\s*=\s*["']?(javascript:|data:)/i,
    field: 'request',
    severity: 'high',
    score: 77,
    category: 'xss',
    description: 'Video poster with dangerous protocol',
    recommendation: 'Validate video poster URLs'
  },
  {
    id: 'xss-track-src',
    name: 'XSS - Track Source XSS',
    pattern: /<track[^>]+src\s*=|<source[^>]+src\s*=\s*["']?(data:|javascript:)/i,
    field: 'request',
    severity: 'high',
    score: 75,
    category: 'xss',
    description: 'Audio/video track source with XSS',
    recommendation: 'Validate media source URLs'
  },
  {
    id: 'xss-marquee-behavior',
    name: 'XSS - Marquee Behavior XSS',
    pattern: /<marquee[^>]+behavior\s*=|onstart|onfinish/i,
    field: 'request',
    severity: 'medium',
    score: 68,
    category: 'xss',
    description: 'Marquee element XSS (legacy)',
    recommendation: 'Remove marquee tags'
  },
  {
    id: 'xss-picture-srcset',
    name: 'XSS - Picture/Srcset XSS',
    pattern: /<picture[\s\S]*?srcset\s*=\s*"[^"]*javascript:|srcset\s*=\s*"[^"]*data:/i,
    field: 'request',
    severity: 'high',
    score: 76,
    category: 'xss',
    description: 'Picture element srcset injection',
    recommendation: 'Validate srcset URLs'
  },
  {
    id: 'xss-isindex',
    name: 'XSS - isindex Tag XSS',
    pattern: /<isindex[\s\S]*?(?:prompt|on\w+)/i,
    field: 'request',
    severity: 'medium',
    score: 60,
    category: 'xss',
    description: 'Deprecated isindex tag exploitation',
    recommendation: 'Remove isindex tags'
  },
  {
    id: 'xss-label-for-xss',
    name: 'XSS - Label for Attribute',
    pattern: /<label[^>]+for\s*=\s*["'][\s\S]*?(?:on\w+|javascript)/i,
    field: 'request',
    severity: 'medium',
    score: 65,
    category: 'xss',
    description: 'Label for attribute combined with event handlers',
    recommendation: 'Validate label for references'
  },
  {
    id: 'xss-output-tag',
    name: 'XSS - Output Tag XSS',
    pattern: /<output[^>]*\son\w+\s*=/i,
    field: 'request',
    severity: 'high',
    score: 72,
    category: 'xss',
    description: 'Output element with event handlers',
    recommendation: 'Sanitize output elements'
  },
  {
    id: 'xss-datalist-xss',
    name: 'XSS - Datalist XSS',
    pattern: /<datalist[^>]*\s(?:on\w+|id\s*=.*on\w+)/i,
    field: 'request',
    severity: 'high',
    score: 71,
    category: 'xss',
    description: 'Datalist element XSS',
    recommendation: 'Sanitize datalist elements'
  },
  {
    id: 'xss-meter-progress',
    name: 'XSS - Meter/Progress Elements',
    pattern: /<(?:meter|progress)[^>]*\son\w+\s*=/i,
    field: 'request',
    severity: 'high',
    score: 70,
    category: 'xss',
    description: 'Meter/Progress element with handlers',
    recommendation: 'Remove event handlers from elements'
  },
  {
    id: 'xss-ruby-annotation',
    name: 'XSS - Ruby Annotation XSS',
    pattern: /<ruby[\s\S]*?rt[\s\S]*?on\w+\s*=/i,
    field: 'request',
    severity: 'medium',
    score: 62,
    category: 'xss',
    description: 'Ruby annotation with XSS',
    recommendation: 'Sanitize ruby tags'
  },
  {
    id: 'xss-details-summary',
    name: 'XSS - Details/Summary XSS',
    pattern: /<(?:details|summary)[^>]*\son(?:toggle|click|load|error)\s*=/i,
    field: 'request',
    severity: 'high',
    score: 73,
    category: 'xss',
    description: 'Details/Summary element with handlers',
    recommendation: 'Sanitize details/summary elements'
  },
  {
    id: 'xss-noscript-injection',
    name: 'XSS - Noscript Tag Injection',
    pattern: /<noscript[\s\S]*?<(?:img|script|svg|iframe)/i,
    field: 'request',
    severity: 'high',
    score: 79,
    category: 'xss',
    description: 'Noscript tag containing XSS payload',
    recommendation: 'Sanitize noscript content'
  },
  {
    id: 'xss-comment-injection',
    name: 'XSS - HTML Comment Injection',
    pattern: /<!--[\s\S]*?(?:<script|on\w+|javascript:)/i,
    field: 'request',
    severity: 'high',
    score: 74,
    category: 'xss',
    description: 'XSS payload hidden in HTML comments',
    recommendation: 'Remove comments or sanitize'
  },
  {
    id: 'xss-cdata-injection',
    name: 'XSS - CDATA Injection',
    pattern: /<!\[CDATA\[[\s\S]*?(?:<script|javascript:)/i,
    field: 'request',
    severity: 'high',
    score: 73,
    category: 'xss',
    description: 'XSS in XML CDATA sections',
    recommendation: 'Sanitize CDATA content'
  },
  {
    id: 'xss-plaintext-tag',
    name: 'XSS - Plaintext Tag',
    pattern: /<plaintext[\s\S]*?>|<listing[\s\S]*?>/i,
    field: 'request',
    severity: 'high',
    score: 72,
    category: 'xss',
    description: 'Plaintext/listing tags for content bypass',
    recommendation: 'Remove deprecated plaintext/listing tags'
  },
  {
    id: 'xss-xmp-tag',
    name: 'XSS - XMP Tag XSS',
    pattern: /<xmp[\s\S]*?>[\s\S]*?<script|<xmp[\s\S]*?on\w+/i,
    field: 'request',
    severity: 'high',
    score: 71,
    category: 'xss',
    description: 'XMP tag exploitation',
    recommendation: 'Remove XMP tags'
  },
  {
    id: 'xss-tabindex-focus',
    name: 'XSS - Tabindex/Autofocus XSS',
    pattern: /tabindex\s*=\s*[-\d]+|autofocus\s*=|autoplay\s*=.*\s(?:on\w+|script)/i,
    field: 'request',
    severity: 'medium',
    score: 69,
    category: 'xss',
    description: 'Tabindex/Autofocus combined with handlers',
    recommendation: 'Validate autofocus usage'
  },
  {
    id: 'xss-contextmenu-attr',
    name: 'XSS - Contextmenu Attribute',
    pattern: /contextmenu\s*=\s*["'][^"']*<|contextmenu[\s\S]*?(?:script|on\w+)/i,
    field: 'request',
    severity: 'medium',
    score: 64,
    category: 'xss',
    description: 'Contextmenu attribute XSS',
    recommendation: 'Validate contextmenu references'
  },
  {
    id: 'xss-usemap-attr',
    name: 'XSS - Usemap Area XSS',
    pattern: /<map[\s\S]*?<area[\s\S]*?(?:href\s*=\s*javascript:|on\w+)/i,
    field: 'request',
    severity: 'high',
    score: 74,
    category: 'xss',
    description: 'Image map area element XSS',
    recommendation: 'Sanitize map/area elements'
  },
  {
    id: 'xss-fieldset-legend',
    name: 'XSS - Fieldset/Legend XSS',
    pattern: /<fieldset[\s\S]*?on\w+\s*=|<legend[\s\S]*?on\w+\s*=/i,
    field: 'request',
    severity: 'high',
    score: 70,
    category: 'xss',
    description: 'Fieldset/legend with event handlers',
    recommendation: 'Remove handlers from form elements'
  },
  {
    id: 'xss-optgroup-option',
    name: 'XSS - Select/Option XSS',
    pattern: /<select[\s\S]*?on\w+\s*=|<option[\s\S]*?on\w+\s*=/i,
    field: 'request',
    severity: 'high',
    score: 72,
    category: 'xss',
    description: 'Select/Option element XSS',
    recommendation: 'Sanitize select/option handlers'
  },
  {
    id: 'xss-dialog-modal',
    name: 'XSS - Dialog/Modal XSS',
    pattern: /<dialog[\s\S]*?(?:on\w+|open\s*>[\s\S]*?<script)/i,
    field: 'request',
    severity: 'high',
    score: 73,
    category: 'xss',
    description: 'Dialog element with handlers',
    recommendation: 'Sanitize dialog elements'
  },
  {
    id: 'xss-template-tag',
    name: 'XSS - Template Tag Content',
    pattern: /<template[\s\S]*?>[\s\S]*?<(?:script|img\s+on\w+)/i,
    field: 'request',
    severity: 'high',
    score: 76,
    category: 'xss',
    description: 'Template tag with embedded scripts',
    recommendation: 'Sanitize template content'
  },
  {
    id: 'xss-slot-xss',
    name: 'XSS - Web Component Slot XSS',
    pattern: /<slot[\s\S]*?name\s*=[\s\S]*?(?:script|on\w+)/i,
    field: 'request',
    severity: 'high',
    score: 74,
    category: 'xss',
    description: 'Web component slot injection',
    recommendation: 'Sanitize slot content'
  },
  {
    id: 'xss-shadow-dom',
    name: 'XSS - Shadow DOM Injection',
    pattern: /attachShadow|shadow-root|shadowRoot|slot\s*=|part\s*=/i,
    field: 'request',
    severity: 'high',
    score: 77,
    category: 'xss',
    description: 'Shadow DOM manipulation',
    recommendation: 'Validate shadow DOM usage'
  },
  {
    id: 'xss-attribute-quotes-bypass',
    name: 'XSS - Unquoted Attribute Bypass',
    pattern: /\s+on\w+=/,
    field: 'request',
    severity: 'high',
    score: 79,
    category: 'xss',
    description: 'Event handler without quotes',
    recommendation: 'Require quoted attributes'
  },
  {
    id: 'xss-newline-injection',
    name: 'XSS - Newline/Carriage Return Injection',
    pattern: /(?:%0A|%0D|\r|\n)\s*(?:on\w+|script|javascript:)/i,
    field: 'request',
    severity: 'high',
    score: 75,
    category: 'xss',
    description: 'Line break for XSS filter bypass',
    recommendation: 'Normalize line breaks'
  },
  {
    id: 'xss-null-byte-injection',
    name: 'XSS - Null Byte Injection',
    pattern: /%00|\\x00|\\u0000|%u0000/,
    field: 'request',
    severity: 'high',
    score: 73,
    category: 'xss',
    description: 'Null byte for XSS bypass',
    recommendation: 'Strip null bytes'
  },
  {
    id: 'xss-mixed-encoding',
    name: 'XSS - Mixed Encoding Bypass',
    pattern: /(?:%|&#|\\x|\\u)[0-9a-fA-F]+.*(?:%|&#|\\x|\\u)[0-9a-fA-F]+.*(?:script|on\w+)/i,
    field: 'request',
    severity: 'high',
    score: 78,
    category: 'xss',
    description: 'Multiple encoding layers for bypass',
    recommendation: 'Recursively decode and validate'
  },
  {
    id: 'xss-rtl-override',
    name: 'XSS - RTL Override (U+202E)',
    pattern: /\\u202e|%E2%80%AE|&#8238;|rtlmark|rtl-override/i,
    field: 'request',
    severity: 'medium',
    score: 61,
    category: 'xss',
    description: 'Right-to-left override for obfuscation',
    recommendation: 'Validate text direction'
  },
  {
    id: 'xss-zero-width-chars',
    name: 'XSS - Zero-Width Character Bypass',
    pattern: /\\u200b|\\u200c|\\u200d|\\ufeff|%E2%80%8B|%E2%80%8C|%E2%80%8D/i,
    field: 'request',
    severity: 'medium',
    score: 62,
    category: 'xss',
    description: 'Zero-width characters for bypass',
    recommendation: 'Remove zero-width characters'
  },
  {
    id: 'xss-combining-chars',
    name: 'XSS - Combining Characters Bypass',
    pattern: /[\u0300-\u036F]{3,}|combining.*mark/i,
    field: 'request',
    severity: 'medium',
    score: 60,
    category: 'xss',
    description: 'Combining diacritical marks for bypass',
    recommendation: 'Normalize Unicode'
  },
  {
    id: 'xss-no-break-space',
    name: 'XSS - No-Break Space Bypass',
    pattern: /\\u00a0|%C2%A0|&#160;|\\240/,
    field: 'request',
    severity: 'medium',
    score: 58,
    category: 'xss',
    description: 'No-break space for filter bypass',
    recommendation: 'Normalize whitespace'
  },
  {
    id: 'xss-variation-selectors',
    name: 'XSS - Variation Selector Bypass',
    pattern: /\\ufe00|\\ufe01|%EF%B8%80|variation.?selector/i,
    field: 'request',
    severity: 'medium',
    score: 59,
    category: 'xss',
    description: 'Unicode variation selectors',
    recommendation: 'Strip variation selectors'
  },
  {
    id: 'xss-soft-hyphen',
    name: 'XSS - Soft Hyphen Bypass',
    pattern: /\\u00ad|%C2%AD|&#173;|soft.?hyphen/i,
    field: 'request',
    severity: 'low',
    score: 45,
    category: 'xss',
    description: 'Soft hyphen for bypass',
    recommendation: 'Strip soft hyphens'
  },
  {
    id: 'xss-bidi-override-complex',
    name: 'XSS - Complex Bidi Override Chain',
    pattern: /(?:\\u202[abed]){2,}|bidi.*override.*override/i,
    field: 'request',
    severity: 'medium',
    score: 63,
    category: 'xss',
    description: 'Multiple bidi control characters',
    recommendation: 'Limit bidi control usage'
  },
  {
    id: 'xss-form-attribute-confusion',
    name: 'XSS - Form Attribute Confusion',
    pattern: /form\s*=|formenctype\s*=|formmethod\s*=|formnovalidate|formtarget\s*=/i,
    field: 'request',
    severity: 'high',
    score: 71,
    category: 'xss',
    description: 'Form attributes manipulation',
    recommendation: 'Validate form references'
  },
  {
    id: 'xss-input-type-confusion',
    name: 'XSS - Input Type Confusion',
    pattern: /type\s*=\s*["'](?:image|button|submit|reset)["'][\s\S]*?(?:on\w+|src\s*=)/i,
    field: 'request',
    severity: 'high',
    score: 70,
    category: 'xss',
    description: 'Input type bypass with handlers',
    recommendation: 'Sanitize input elements'
  },
  {
    id: 'xss-button-formaction',
    name: 'XSS - Button Formaction Override',
    pattern: /<button[\s\S]*?formaction\s*=\s*["']?(?!https?:\/\/trusted)/i,
    field: 'request',
    severity: 'high',
    score: 76,
    category: 'xss',
    description: 'Button formaction attribute hijacking',
    recommendation: 'Whitelist allowed actions'
  },
  {
    id: 'xss-css-import-url',
    name: 'XSS - CSS @import URL',
    pattern: /@import\s+url\s*\(\s*["']?(?:javascript:|data:|about:)/i,
    field: 'request',
    severity: 'high',
    score: 75,
    category: 'xss',
    description: 'CSS @import with dangerous URLs',
    recommendation: 'Validate CSS imports'
  },
  {
    id: 'xss-css-behavior',
    name: 'XSS - CSS Behavior Property',
    pattern: /behavior\s*:\s*url|binding\s*:\s*url/i,
    field: 'request',
    severity: 'high',
    score: 77,
    category: 'xss',
    description: 'CSS behavior/binding XSS',
    recommendation: 'Remove or sanitize CSS'
  },
  {
    id: 'xss-moz-binding',
    name: 'XSS - -moz-binding XSS',
    pattern: /-moz-binding\s*:\s*url|xbl:|expression\s*\(/i,
    field: 'request',
    severity: 'high',
    score: 76,
    category: 'xss',
    description: 'Mozilla-specific XSS vectors',
    recommendation: 'Remove vendor-specific properties'
  },
  {
    id: 'xss-resource-hint-xss',
    name: 'XSS - Link Resource Hint XSS',
    pattern: /<link\s+(?:rel=|href=)[\s\S]*?(?:rel="(?:prefetch|preload|dns-prefetch|preconnect)"|href\s*=\s*["']?(?:javascript:|data:))/i,
    field: 'request',
    severity: 'high',
    score: 72,
    category: 'xss',
    description: 'Link resource hints with XSS',
    recommendation: 'Validate link resources'
  },
  {
    id: 'xss-crossorigin-bypass',
    name: 'XSS - Crossorigin Attribute Abuse',
    pattern: /crossorigin\s*=\s*["']?anonymous["']?[\s\S]*?(?:on\w+|src\s*=\s*["']?(?:javascript:|data:))/i,
    field: 'request',
    severity: 'high',
    score: 68,
    category: 'xss',
    description: 'Crossorigin with malicious payload',
    recommendation: 'Validate CORS attributes'
  },
  {
    id: 'xss-integrity-bypass',
    name: 'XSS - Integrity Attribute Bypass',
    pattern: /integrity\s*=\s*["']{2}|integrity=""|integrity=''/i,
    field: 'request',
    severity: 'high',
    score: 79,
    category: 'xss',
    description: 'Empty integrity attribute for bypass',
    recommendation: 'Require valid integrity hashes'
  }
];
